# Generated by Django 2.2.6 on 2019-11-14 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20191112_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url_amazon',
            field=models.CharField(db_index=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='url_flipkart',
            field=models.CharField(db_index=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='url_jiomart',
            field=models.CharField(db_index=True, max_length=250),
        ),
    ]
